apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad
  namespace: default
  labels:
    team: flex
spec:
  image: repo.adeo.no:5443/digisyfo/sykepengesoknad
  liveness:
    path: /health/isAlive
    initialDelay: 60
  readiness:
    path: /health/isReady
    initialDelay: 60
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://tjenester-q1.nav.no/sykepengesoknad"
  vault:
    enabled: true
  env:
    - name: sykefravaerapi
      value: "https://tjenester-q1.nav.no/syforest"
    - name: loginservice
      value: "https://loginservice-q.nav.no/login"
    - name: syfounleashapi
      value: "https://syfounleash.nais.oera-q.local"
    - name: appres.cms
      value: "https://appres-q1.nav.no"
    - name: syfoapi-syfoteksterapi
      value: "https://syfoapi.nais.oera-q.local/syfotekster/api/tekster"
    - name: syfoapi-syfosoknadapi
      value: "https://syfoapi.nais.oera-q.local/syfosoknad/api"

