const landliste = [
    'Afghanistan',
    'Albania',
    'Algerie',
    'Amerikansk Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antigua og Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Aserbajdsjan',
    'Australia',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belgia',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bosnia-Hercegovina',
    'Botswana',
    'Bouvetøya',
    'Brasil',
    'Britisk territorium i Indiahavet',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burma',
    'Burundi',
    'Canada',
    'Caymanøyene',
    'Chile',
    'Christmasøya',
    'Colombia',
    'Cookøyene',
    'Costa Rica',
    'Cuba',
    'Curaçao',
    'Danmark',
    'De forente arabiske emirater',
    'De okkuperte palestinske områdene',
    'Den dominikanske republikk',
    'Den sentralafrikanske republikk',
    'Djibouti',
    'Dominica',
    'Ecuador',
    'Egypt',
    'Ekvatorial-Guinea',
    'El Salvador',
    'Elfenbenskysten',
    'Eritrea',
    'Estland',
    'Etiopia',
    'Falklandsøyene',
    'Fiji',
    'Filippinene',
    'Finland',
    'Frankrike',
    'Fransk Guyana',
    'Fransk Polynesia',
    'Færøyene',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Gibraltar',
    'Grenada',
    'Grønland',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Heard- og McDonald-øyene',
    'Hellas',
    'Honduras',
    'Hongkong',
    'Hviterussland',
    'India',
    'Indonesia',
    'Irak',
    'Iran',
    'Irland',
    'Island',
    'Israel',
    'Italia',
    'Jamaica',
    'Japan',
    'Jemen',
    'Jersey',
    'Jomfruøyene (Britisk)',
    'Jomfruøyene (USA)',
    'Jordan',
    'Kambodsja',
    'Kamerun',
    'Kapp Verde',
    'Karibisk Nederland',
    'Kasakhstan',
    'Kenya',
    'Kina',
    'Kirgisistan',
    'Kiribati',
    'Kokosøyene',
    'Komorene',
    'Kongo',
    'Kongo-Brazzaville',
    'Kosovo',
    'Kroatia',
    'Kuwait',
    'Kypros',
    'Laos',
    'Latvia',
    'Lesotho',
    'Libanon',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Litauen',
    'Luxembourg',
    'Macao',
    'Madagaskar',
    'Makedonia',
    'Malawi',
    'Malaysia',
    'Maldivene',
    'Mali',
    'Malta',
    'Man',
    'Marokko',
    'Marshalløyene',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Mikronesiaføderasjonen',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Mosambik',
    'Namibia',
    'Nauru',
    'Nederland',
    'Nepal',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Nord-Korea',
    'Nord-Marianene',
    'Norfolk Island',
    'Norge',
    'Ny-Caledonia',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua Ny-Guinea',
    'Paraguay',
    'Peru',
    'Pitcairn',
    'Polen',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Réunion',
    'Romania',
    'Russland',
    'Rwanda',
    'Saint Kitts og Nevis',
    'Saint Lucia',
    'Saint Vincent og Grenadinene',
    'Saint-Barthélemy',
    'Saint-Martin',
    'Saint-Pierre-et-Miquelon',
    'Salomonøyene',
    'Samoa',
    'San Marino',
    'São Tomé og Príncipe',
    'Saudi-Arabia',
    'Senegal',
    'Serbia',
    'Seychellene',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten (Nederlandsk del)',
    'Slovakia',
    'Slovenia',
    'Somalia',
    'Spania',
    'Sri Lanka',
    'St. Helena',
    'Storbritannia',
    'Sudan',
    'Surinam',
    'Svalbard og Jan Mayen',
    'Sveits',
    'Sverige',
    'Swaziland',
    'Syria',
    'Sør-Afrika',
    'Sør-Georgia og de søre Sandwichøyene',
    'Sør-Korea',
    'Sør-Sudan',
    'Søre franske territorier',
    'Tadsjikistan',
    'Taiwan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad og Tobago',
    'Tsjad',
    'Tsjekkia',
    'Tunisia',
    'Turkmenistan',
    'Turks- og Caicosøyene',
    'Tuvalu',
    'Tyrkia',
    'Tyskland',
    'Uganda',
    'Ukraina',
    'Ungarn',
    'Uruguay',
    'USA',
    'USA, mindre, utenforliggende øyer',
    'Usbekistan',
    'Vanuatu',
    'Vatikanstaten',
    'Venezuela',
    'Vest-Sahara',
    'Vietnam',
    'Wallis- og Futunaøyene',
    'Zambia',
    'Zimbabwe',
    'Øst-Timor',
    'Østerrike',
    'Åland',
];

export default landliste;
