import { setLedetekster } from '@navikt/digisyfo-npm';
import fraBackendsoknadTilInitiellSoknad from '../utils/fraBackendsoknadTilInitiellSoknad';
import { parseSoknad } from '../data/soknader/soknader';
import expect from '../../../test/expect';
import validerGraderteArbeidssporsmal from './validerGraderteArbeidssporsmal';

/* eslint-disable max-len */

describe('validerGraderteArbeidssporsmal', () => {
    beforeEach(() => {
        setLedetekster({
            'soknad.feilmelding.hvor_mye_timer_verdi.min': 'Timene du skrev inn tyder på at du har jobbet mindre enn %MIN% %. Du må enten svare nei på spørsmålet over eller endre antall timer her.',
        });
    });

    it('Skal klage når oppgitt timer i beregnet arbeidsgrad utgjør mindre enn arbeidsgrad i sykmeldingen', () => {
        const soknad = {
            id: 'a6337d3a-517c-4aa8-a019-17a78246d9cc',
            aktorId: '1924473393808',
            sykmeldingId: '8a8b9a41-b8ee-4ff3-947b-62fffe8bfc0d',
            soknadstype: 'ARBEIDSTAKERE',
            status: 'NY',
            fom: '2019-05-07',
            tom: '2019-05-15',
            opprettetDato: '2019-05-16',
            innsendtDato: null,
            sendtTilNAVDato: null,
            sendtTilArbeidsgiverDato: null,
            avbruttDato: null,
            startSykeforlop: '2019-05-07',
            sykmeldingUtskrevet: '2019-05-07',
            arbeidsgiver: {
                navn: 'ÅSEN BOFELLESSKAP',
                orgnummer: '995816598',
            },
            korrigerer: null,
            korrigertAv: null,
            arbeidssituasjon: 'ARBEIDSTAKER',
            soknadPerioder: [
                {
                    fom: '2019-05-07',
                    tom: '2019-05-15',
                    grad: 40,
                },
            ],
            sporsmal: [
                {
                    id: '215257',
                    tag: 'FERIE_V2',
                    sporsmalstekst: 'Tok du ut ferie som var avtalt med arbeidsgiveren din mens du var sykmeldt 11. - 19. mai 2019?',
                    undertekst: null,
                    svartype: 'JA_NEI',
                    min: null,
                    max: null,
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{
                        verdi: 'NEI',
                    }],
                    undersporsmal: [{
                        id: '215258',
                        tag: 'FERIE_NAR_V2',
                        sporsmalstekst: 'Når tok du ut ferie?',
                        undertekst: null,
                        svartype: 'PERIODER',
                        min: '2019-05-11',
                        max: '2019-05-19',
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: null,
                        svar: [],
                        undersporsmal: [],
                    }],
                },
                {
                    id: '214633',
                    tag: 'JOBBET_DU_GRADERT_0',
                    sporsmalstekst: 'I perioden 7. - 15. mai 2019 skulle du jobbe 60 % av ditt normale arbeid hos ÅSEN BOFELLESSKAP. Jobbet du mer enn dette?',
                    undertekst: null,
                    svartype: 'JA_NEI',
                    min: null,
                    max: null,
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{
                        verdi: 'JA',
                    }],
                    undersporsmal: [
                        {
                            id: '214634',
                            tag: 'HVOR_MANGE_TIMER_PER_UKE_0',
                            sporsmalstekst: 'Hvor mange timer jobbet du per uke før du ble sykmeldt?',
                            undertekst: 'timer per uke',
                            svartype: 'TALL',
                            min: '1',
                            max: '150',
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [{
                                verdi: '37,5',
                            }],
                            undersporsmal: [],
                        },
                        {
                            id: '214635',
                            tag: 'HVOR_MYE_HAR_DU_JOBBET_0',
                            sporsmalstekst: 'Hvor mye jobbet du totalt 7. - 15. mai 2019 hos ÅSEN BOFELLESSKAP?',
                            undertekst: null,
                            svartype: 'RADIO_GRUPPE_TIMER_PROSENT',
                            min: null,
                            max: null,
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [
                                {
                                    id: '214636',
                                    tag: 'HVOR_MYE_PROSENT_0',
                                    sporsmalstekst: 'prosent',
                                    undertekst: null,
                                    svartype: 'RADIO',
                                    min: null,
                                    max: null,
                                    pavirkerAndreSporsmal: false,
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [],
                                    undersporsmal: [
                                        {
                                            id: '214637',
                                            tag: 'HVOR_MYE_PROSENT_VERDI_0',
                                            sporsmalstekst: null,
                                            undertekst: 'prosent',
                                            svartype: 'TALL',
                                            min: '61',
                                            max: '99',
                                            pavirkerAndreSporsmal: false,
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [],
                                            undersporsmal: [],
                                        },
                                    ],
                                },
                                {
                                    id: '214638',
                                    tag: 'HVOR_MYE_TIMER_0',
                                    sporsmalstekst: 'timer',
                                    undertekst: null,
                                    svartype: 'RADIO',
                                    min: null,
                                    max: null,
                                    pavirkerAndreSporsmal: false,
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [{
                                        verdi: 'CHECKED',
                                    }],
                                    undersporsmal: [
                                        {
                                            id: '214639',
                                            tag: 'HVOR_MYE_TIMER_VERDI_0',
                                            sporsmalstekst: null,
                                            undertekst: 'timer totalt',
                                            svartype: 'TALL',
                                            min: '1',
                                            max: '193',
                                            pavirkerAndreSporsmal: false,
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [{
                                                verdi: '31',
                                            }],
                                            undersporsmal: [],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        };
        const values = fraBackendsoknadTilInitiellSoknad(soknad);
        const feilmeldinger = validerGraderteArbeidssporsmal(soknad.sporsmal, values, parseSoknad(soknad));
        expect(feilmeldinger.HVOR_MYE_TIMER_VERDI_0).to.equal('Timene du skrev inn tyder på at du har jobbet mindre enn 60 %. Du må enten svare nei på spørsmålet over eller endre antall timer her.');
    });

    it('Skal ikke klage når oppgitt timer i beregnet arbeidsgrad utgjør mer enn arbeidsgrad i sykmeldingen', () => {
        const soknad = {
            id: 'a6337d3a-517c-4aa8-a019-17a78246d9cc',
            aktorId: '1924473393808',
            sykmeldingId: '8a8b9a41-b8ee-4ff3-947b-62fffe8bfc0d',
            soknadstype: 'ARBEIDSTAKERE',
            status: 'NY',
            fom: '2019-05-07',
            tom: '2019-05-15',
            opprettetDato: '2019-05-16',
            innsendtDato: null,
            sendtTilNAVDato: null,
            sendtTilArbeidsgiverDato: null,
            avbruttDato: null,
            startSykeforlop: '2019-05-07',
            sykmeldingUtskrevet: '2019-05-07',
            arbeidsgiver: {
                navn: 'ÅSEN BOFELLESSKAP',
                orgnummer: '995816598',
            },
            korrigerer: null,
            korrigertAv: null,
            arbeidssituasjon: 'ARBEIDSTAKER',
            soknadPerioder: [
                {
                    fom: '2019-05-07',
                    tom: '2019-05-15',
                    grad: 40,
                },
            ],
            sporsmal: [
                {
                    id: '215257',
                    tag: 'FERIE_V2',
                    sporsmalstekst: 'Tok du ut ferie som var avtalt med arbeidsgiveren din mens du var sykmeldt 11. - 19. mai 2019?',
                    undertekst: null,
                    svartype: 'JA_NEI',
                    min: null,
                    max: null,
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{
                        verdi: 'NEI',
                    }],
                    undersporsmal: [{
                        id: '215258',
                        tag: 'FERIE_NAR_V2',
                        sporsmalstekst: 'Når tok du ut ferie?',
                        undertekst: null,
                        svartype: 'PERIODER',
                        min: '2019-05-11',
                        max: '2019-05-19',
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: null,
                        svar: [],
                        undersporsmal: [],
                    }],
                },
                {
                    id: '214633',
                    tag: 'JOBBET_DU_GRADERT_0',
                    sporsmalstekst: 'I perioden 7. - 15. mai 2019 skulle du jobbe 60 % av ditt normale arbeid hos ÅSEN BOFELLESSKAP. Jobbet du mer enn dette?',
                    undertekst: null,
                    svartype: 'JA_NEI',
                    min: null,
                    max: null,
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{
                        verdi: 'JA',
                    }],
                    undersporsmal: [
                        {
                            id: '214634',
                            tag: 'HVOR_MANGE_TIMER_PER_UKE_0',
                            sporsmalstekst: 'Hvor mange timer jobbet du per uke før du ble sykmeldt?',
                            undertekst: 'timer per uke',
                            svartype: 'TALL',
                            min: '1',
                            max: '150',
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [{
                                verdi: '37,5',
                            }],
                            undersporsmal: [],
                        },
                        {
                            id: '214635',
                            tag: 'HVOR_MYE_HAR_DU_JOBBET_0',
                            sporsmalstekst: 'Hvor mye jobbet du totalt 7. - 15. mai 2019 hos ÅSEN BOFELLESSKAP?',
                            undertekst: null,
                            svartype: 'RADIO_GRUPPE_TIMER_PROSENT',
                            min: null,
                            max: null,
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [
                                {
                                    id: '214636',
                                    tag: 'HVOR_MYE_PROSENT_0',
                                    sporsmalstekst: 'prosent',
                                    undertekst: null,
                                    svartype: 'RADIO',
                                    min: null,
                                    max: null,
                                    pavirkerAndreSporsmal: false,
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [],
                                    undersporsmal: [
                                        {
                                            id: '214637',
                                            tag: 'HVOR_MYE_PROSENT_VERDI_0',
                                            sporsmalstekst: null,
                                            undertekst: 'prosent',
                                            svartype: 'TALL',
                                            min: '61',
                                            max: '99',
                                            pavirkerAndreSporsmal: false,
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [],
                                            undersporsmal: [],
                                        },
                                    ],
                                },
                                {
                                    id: '214638',
                                    tag: 'HVOR_MYE_TIMER_0',
                                    sporsmalstekst: 'timer',
                                    undertekst: null,
                                    svartype: 'RADIO',
                                    min: null,
                                    max: null,
                                    pavirkerAndreSporsmal: false,
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [{
                                        verdi: 'CHECKED',
                                    }],
                                    undersporsmal: [
                                        {
                                            id: '214639',
                                            tag: 'HVOR_MYE_TIMER_VERDI_0',
                                            sporsmalstekst: null,
                                            undertekst: 'timer totalt',
                                            svartype: 'TALL',
                                            min: '1',
                                            max: '193',
                                            pavirkerAndreSporsmal: false,
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [{
                                                verdi: '32',
                                            }],
                                            undersporsmal: [],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        };
        const values = fraBackendsoknadTilInitiellSoknad(soknad);
        const feilmeldinger = validerGraderteArbeidssporsmal(soknad.sporsmal, values, parseSoknad(soknad));
        expect(feilmeldinger.HVOR_MYE_TIMER_VERDI_0).to.equal(undefined);
    });

    it('Skal ikke klage når oppgitt timer i beregnet arbeidsgrad utgjør mindre enn arbeidsgrad i sykmeldingen hvis man har valgt å oppgi svar i prosent', () => {
        const soknad = {
            id: 'a6337d3a-517c-4aa8-a019-17a78246d9cc',
            aktorId: '1924473393808',
            sykmeldingId: '8a8b9a41-b8ee-4ff3-947b-62fffe8bfc0d',
            soknadstype: 'ARBEIDSTAKERE',
            status: 'NY',
            fom: '2019-05-07',
            tom: '2019-05-15',
            opprettetDato: '2019-05-16',
            innsendtDato: null,
            sendtTilNAVDato: null,
            sendtTilArbeidsgiverDato: null,
            avbruttDato: null,
            startSykeforlop: '2019-05-07',
            sykmeldingUtskrevet: '2019-05-07',
            arbeidsgiver: {
                navn: 'ÅSEN BOFELLESSKAP',
                orgnummer: '995816598',
            },
            korrigerer: null,
            korrigertAv: null,
            arbeidssituasjon: 'ARBEIDSTAKER',
            soknadPerioder: [
                {
                    fom: '2019-05-07',
                    tom: '2019-05-15',
                    grad: 40,
                },
            ],
            sporsmal: [
                {
                    id: '214633',
                    tag: 'JOBBET_DU_GRADERT_0',
                    sporsmalstekst: 'I perioden 7. - 15. mai 2019 skulle du jobbe 60 % av ditt normale arbeid hos ÅSEN BOFELLESSKAP. Jobbet du mer enn dette?',
                    undertekst: null,
                    svartype: 'JA_NEI',
                    min: null,
                    max: null,
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{
                        verdi: 'JA',
                    }],
                    undersporsmal: [
                        {
                            id: '214634',
                            tag: 'HVOR_MANGE_TIMER_PER_UKE_0',
                            sporsmalstekst: 'Hvor mange timer jobbet du per uke før du ble sykmeldt?',
                            undertekst: 'timer per uke',
                            svartype: 'TALL',
                            min: '1',
                            max: '150',
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [{
                                verdi: '37,5',
                            }],
                            undersporsmal: [],
                        },
                        {
                            id: '214635',
                            tag: 'HVOR_MYE_HAR_DU_JOBBET_0',
                            sporsmalstekst: 'Hvor mye jobbet du totalt 7. - 15. mai 2019 hos ÅSEN BOFELLESSKAP?',
                            undertekst: null,
                            svartype: 'RADIO_GRUPPE_TIMER_PROSENT',
                            min: null,
                            max: null,
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [
                                {
                                    id: '214636',
                                    tag: 'HVOR_MYE_PROSENT_0',
                                    sporsmalstekst: 'prosent',
                                    undertekst: null,
                                    svartype: 'RADIO',
                                    min: null,
                                    max: null,
                                    pavirkerAndreSporsmal: false,
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [{
                                        verdi: 'CHECKED',
                                    }],
                                    undersporsmal: [
                                        {
                                            id: '214637',
                                            tag: 'HVOR_MYE_PROSENT_VERDI_0',
                                            sporsmalstekst: null,
                                            undertekst: 'prosent',
                                            svartype: 'TALL',
                                            min: '61',
                                            max: '99',
                                            pavirkerAndreSporsmal: false,
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [],
                                            undersporsmal: [],
                                        },
                                    ],
                                },
                                {
                                    id: '214638',
                                    tag: 'HVOR_MYE_TIMER_0',
                                    sporsmalstekst: 'timer',
                                    undertekst: null,
                                    svartype: 'RADIO',
                                    min: null,
                                    max: null,
                                    pavirkerAndreSporsmal: false,
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [],
                                    undersporsmal: [
                                        {
                                            id: '214639',
                                            tag: 'HVOR_MYE_TIMER_VERDI_0',
                                            sporsmalstekst: null,
                                            undertekst: 'timer totalt',
                                            svartype: 'TALL',
                                            min: '1',
                                            max: '193',
                                            pavirkerAndreSporsmal: false,
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [{
                                                verdi: '4',
                                            }],
                                            undersporsmal: [],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        };
        const values = fraBackendsoknadTilInitiellSoknad(soknad);
        const feilmeldinger = validerGraderteArbeidssporsmal(soknad.sporsmal, values, parseSoknad(soknad));
        expect(feilmeldinger.HVOR_MYE_TIMER_VERDI_0).to.equal(undefined);
    });

    it('Skal ta med ferie- og permisjonsperioder i beregning av arbeidsgrad', () => {
        const soknad = {
            id: 'a4f27ba1-f850-49f0-b314-20b1564b2ef8',
            aktorId: '1924473393808',
            sykmeldingId: '2f3582db-5713-48d4-9de7-286b45886215',
            soknadstype: 'ARBEIDSTAKERE',
            status: 'NY',
            fom: '2019-05-11',
            tom: '2019-05-19',
            opprettetDato: '2019-05-20',
            innsendtDato: null,
            sendtTilNAVDato: null,
            sendtTilArbeidsgiverDato: null,
            avbruttDato: null,
            startSykeforlop: '2019-05-07',
            sykmeldingUtskrevet: '2019-05-11',
            arbeidsgiver: {
                navn: 'ÅSEN BOFELLESSKAP',
                orgnummer: '995816598',
            },
            korrigerer: null,
            korrigertAv: null,
            arbeidssituasjon: 'ARBEIDSTAKER',
            soknadPerioder: [{
                fom: '2019-05-11',
                tom: '2019-05-19',
                grad: 40,
            }],
            sporsmal: [{
                id: '215252',
                tag: 'ANSVARSERKLARING',
                sporsmalstekst: 'Jeg vet at jeg kan miste retten til sykepenger hvis opplysningene jeg gir ikke er riktige eller fullstendige. Jeg vet også at NAV kan holde igjen eller kreve tilbake penger, og at å gi feil opplysninger kan være straffbart.',
                undertekst: null,
                svartype: 'CHECKBOX_PANEL',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: null,
                svar: [{
                    verdi: 'CHECKED',
                }],
                undersporsmal: [],
            }, {
                id: '215253',
                tag: 'EGENMELDINGER',
                sporsmalstekst: 'Vi har registrert at du ble sykmeldt tirsdag 7. mai 2019. Brukte du egenmeldinger og/eller var du sykmeldt i perioden 21. april - 6. mai 2019?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [{
                    verdi: 'NEI',
                }],
                undersporsmal: [{
                    id: '215254',
                    tag: 'EGENMELDINGER_NAR',
                    sporsmalstekst: 'Hvilke dager før 7. mai 2019 var du borte fra jobb?',
                    undertekst: null,
                    svartype: 'PERIODER',
                    min: '2018-11-07',
                    max: '2019-05-06',
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                }],
            }, {
                id: '215255',
                tag: 'TILBAKE_I_ARBEID',
                sporsmalstekst: 'Var du tilbake i fullt arbeid hos ÅSEN BOFELLESSKAP før 20. mai 2019?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: true,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [{
                    verdi: 'NEI',
                }],
                undersporsmal: [{
                    id: '215256',
                    tag: 'TILBAKE_NAR',
                    sporsmalstekst: 'Når begynte du å jobbe igjen?',
                    undertekst: null,
                    svartype: 'DATO',
                    min: '2019-05-11',
                    max: '2019-05-19',
                    pavirkerAndreSporsmal: true,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                }],
            }, {
                id: '215257',
                tag: 'FERIE_V2',
                sporsmalstekst: 'Tok du ut ferie som var avtalt med arbeidsgiveren din mens du var sykmeldt 11. - 19. mai 2019?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [{
                    verdi: 'JA',
                }],
                undersporsmal: [{
                    id: '215258',
                    tag: 'FERIE_NAR_V2',
                    sporsmalstekst: 'Når tok du ut ferie?',
                    undertekst: null,
                    svartype: 'PERIODER',
                    min: '2019-05-11',
                    max: '2019-05-19',
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{
                        verdi: '{"fom":"13.05.2019","tom":"14.05.2019"}',
                    }],
                    undersporsmal: [],
                }],
            }, {
                id: '215259',
                tag: 'PERMISJON_V2',
                sporsmalstekst: 'Tok du permisjon mens du var sykmeldt 11. - 19. mai 2019?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [{
                    verdi: 'JA',
                }],
                undersporsmal: [{
                    id: '215260',
                    tag: 'PERMISJON_NAR_V2',
                    sporsmalstekst: 'Når tok du permisjon?',
                    undertekst: null,
                    svartype: 'PERIODER',
                    min: '2019-05-11',
                    max: '2019-05-19',
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{
                        verdi: '{"fom":"17.05.2019","tom":"17.05.2019"}',
                    }],
                    undersporsmal: [],
                }],
            }, {
                id: '215261',
                tag: 'UTLAND_V2',
                sporsmalstekst: 'Var du på reise utenfor Norge mens du var sykmeldt 11. - 19. mai 2019?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [{
                    verdi: 'NEI',
                }],
                undersporsmal: [{
                    id: '215262',
                    tag: 'UTLAND_NAR_V2',
                    sporsmalstekst: 'Når var du utenfor Norge?',
                    undertekst: null,
                    svartype: 'PERIODER',
                    min: '2019-05-11',
                    max: '2019-05-19',
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                }],
            }, {
                id: '215263',
                tag: 'JOBBET_DU_GRADERT_0',
                sporsmalstekst: 'I perioden 11. - 19. mai 2019 skulle du jobbe 60 % av ditt normale arbeid hos ÅSEN BOFELLESSKAP. Jobbet du mer enn dette?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [{
                    verdi: 'JA',
                }],
                undersporsmal: [{
                    id: '215264',
                    tag: 'HVOR_MANGE_TIMER_PER_UKE_0',
                    sporsmalstekst: 'Hvor mange timer jobbet du per uke før du ble sykmeldt?',
                    undertekst: 'timer per uke',
                    svartype: 'TALL',
                    min: '1',
                    max: '150',
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{
                        verdi: '37,5',
                    }],
                    undersporsmal: [],
                }, {
                    id: '215265',
                    tag: 'HVOR_MYE_HAR_DU_JOBBET_0',
                    sporsmalstekst: 'Hvor mye jobbet du totalt 11. - 19. mai 2019 hos ÅSEN BOFELLESSKAP?',
                    undertekst: null,
                    svartype: 'RADIO_GRUPPE_TIMER_PROSENT',
                    min: null,
                    max: null,
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [{
                        id: '215266',
                        tag: 'HVOR_MYE_PROSENT_0',
                        sporsmalstekst: 'prosent',
                        undertekst: null,
                        svartype: 'RADIO',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [],
                        undersporsmal: [{
                            id: '215267',
                            tag: 'HVOR_MYE_PROSENT_VERDI_0',
                            sporsmalstekst: null,
                            undertekst: 'prosent',
                            svartype: 'TALL',
                            min: '61',
                            max: '99',
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                        }],
                    }, {
                        id: '215268',
                        tag: 'HVOR_MYE_TIMER_0',
                        sporsmalstekst: 'timer',
                        undertekst: null,
                        svartype: 'RADIO',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [{
                            verdi: 'CHECKED',
                        }],
                        undersporsmal: [{
                            id: '215269',
                            tag: 'HVOR_MYE_TIMER_VERDI_0',
                            sporsmalstekst: null,
                            undertekst: 'timer totalt',
                            svartype: 'TALL',
                            min: '1',
                            max: '193',
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [{
                                verdi: '10',
                            }],
                            undersporsmal: [],
                        }],
                    }],
                }],
            }, {
                id: '215270',
                tag: 'ANDRE_INNTEKTSKILDER',
                sporsmalstekst: 'Har du andre inntektskilder enn ÅSEN BOFELLESSKAP?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [],
                undersporsmal: [{
                    id: '215271',
                    tag: 'HVILKE_ANDRE_INNTEKTSKILDER',
                    sporsmalstekst: 'Hvilke andre inntektskilder har du?',
                    undertekst: 'Du trenger ikke oppgi penger fra NAV',
                    svartype: 'CHECKBOX_GRUPPE',
                    min: null,
                    max: null,
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [{
                        id: '215272',
                        tag: 'INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD',
                        sporsmalstekst: 'andre arbeidsforhold',
                        undertekst: null,
                        svartype: 'CHECKBOX',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [],
                        undersporsmal: [{
                            id: '215273',
                            tag: 'INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD_ER_DU_SYKMELDT',
                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                            undertekst: null,
                            svartype: 'JA_NEI',
                            min: null,
                            max: null,
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                        }],
                    }, {
                        id: '215274',
                        tag: 'INNTEKTSKILDE_SELVSTENDIG',
                        sporsmalstekst: 'selvstendig næringsdrivende',
                        undertekst: null,
                        svartype: 'CHECKBOX',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [],
                        undersporsmal: [{
                            id: '215275',
                            tag: 'INNTEKTSKILDE_SELVSTENDIG_ER_DU_SYKMELDT',
                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                            undertekst: null,
                            svartype: 'JA_NEI',
                            min: null,
                            max: null,
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                        }],
                    }, {
                        id: '215276',
                        tag: 'INNTEKTSKILDE_SELVSTENDIG_DAGMAMMA',
                        sporsmalstekst: 'dagmamma',
                        undertekst: null,
                        svartype: 'CHECKBOX',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [],
                        undersporsmal: [{
                            id: '215277',
                            tag: 'INNTEKTSKILDE_SELVSTENDIG_DAGMAMMA_ER_DU_SYKMELDT',
                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                            undertekst: null,
                            svartype: 'JA_NEI',
                            min: null,
                            max: null,
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                        }],
                    }, {
                        id: '215278',
                        tag: 'INNTEKTSKILDE_JORDBRUKER',
                        sporsmalstekst: 'jordbruk / fiske / reindrift',
                        undertekst: null,
                        svartype: 'CHECKBOX',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [],
                        undersporsmal: [{
                            id: '215279',
                            tag: 'INNTEKTSKILDE_JORDBRUKER_ER_DU_SYKMELDT',
                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                            undertekst: null,
                            svartype: 'JA_NEI',
                            min: null,
                            max: null,
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                        }],
                    }, {
                        id: '215280',
                        tag: 'INNTEKTSKILDE_FRILANSER',
                        sporsmalstekst: 'frilanser',
                        undertekst: null,
                        svartype: 'CHECKBOX',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [],
                        undersporsmal: [{
                            id: '215281',
                            tag: 'INNTEKTSKILDE_FRILANSER_ER_DU_SYKMELDT',
                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                            undertekst: null,
                            svartype: 'JA_NEI',
                            min: null,
                            max: null,
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                        }],
                    }, {
                        id: '215282',
                        tag: 'INNTEKTSKILDE_ANNET',
                        sporsmalstekst: 'annet',
                        undertekst: null,
                        svartype: 'CHECKBOX',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: null,
                        svar: [],
                        undersporsmal: [],
                    }],
                }],
            }, {
                id: '215283',
                tag: 'UTDANNING',
                sporsmalstekst: 'Har du vært under utdanning i løpet av perioden 11. - 19. mai 2019?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [],
                undersporsmal: [{
                    id: '215284',
                    tag: 'UTDANNING_START',
                    sporsmalstekst: 'Når startet du på utdanningen?',
                    undertekst: null,
                    svartype: 'DATO',
                    min: null,
                    max: '2019-05-19',
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                }, {
                    id: '215285',
                    tag: 'FULLTIDSSTUDIUM',
                    sporsmalstekst: 'Er utdanningen et fulltidsstudium?',
                    undertekst: null,
                    svartype: 'JA_NEI',
                    min: null,
                    max: null,
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                }],
            }, {
                id: '215286',
                tag: 'VAER_KLAR_OVER_AT',
                sporsmalstekst: 'Viktig å være klar over:',
                undertekst: '<ul><li>Du kan bare få sykepenger hvis det er din egen sykdom eller skade som hindrer deg i å jobbe. Sosiale eller økonomiske problemer gir ikke rett til sykepenger.</li><li>Du kan miste retten til sykepenger hvis du nekter å opplyse om din egen arbeidsevne, eller hvis du ikke tar imot behandling eller tilrettelegging.</li><li>Retten til sykepenger gjelder bare inntekt du har mottatt som lønn og betalt skatt av på sykmeldingstidspunktet.</li><li>NAV kan innhente opplysninger som er nødvendige for å behandle søknaden.</li><li>Du må melde fra til NAV hvis du satt i varetekt, sonet straff eller var under forvaring i sykmeldingsperioden.</li><li>Fristen for å søke sykepenger er som hovedregel 3 måneder</li></ul><p>Du kan lese mer om rettigheter og plikter på <a href="https://www.nav.no/sykepenger" target="_blank">nav.no/sykepenger</a>.</p>',
                svartype: 'IKKE_RELEVANT',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: null,
                svar: [],
                undersporsmal: [],
            }, {
                id: '215287',
                tag: 'BEKREFT_OPPLYSNINGER',
                sporsmalstekst: 'Jeg har lest all informasjonen jeg har fått i søknaden og bekrefter at opplysningene jeg har gitt er korrekte.',
                undertekst: null,
                svartype: 'CHECKBOX_PANEL',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: null,
                svar: [],
                undersporsmal: [],
            }],
        };
        const values = fraBackendsoknadTilInitiellSoknad(soknad);
        const feilmeldinger = validerGraderteArbeidssporsmal(soknad.sporsmal, values, parseSoknad(soknad));
        expect(feilmeldinger.HVOR_MYE_TIMER_VERDI_0).to.equal(undefined);
    });

    it('Skal ikke med ferie- og permisjonsperioder i beregning av arbeidsgrad dersom disse er fjernet fra søknaden', () => {
        const soknad = {
            id: 'a4f27ba1-f850-49f0-b314-20b1564b2ef8',
            aktorId: '1924473393808',
            sykmeldingId: '2f3582db-5713-48d4-9de7-286b45886215',
            soknadstype: 'ARBEIDSTAKERE',
            status: 'NY',
            fom: '2019-05-11',
            tom: '2019-05-19',
            opprettetDato: '2019-05-20',
            innsendtDato: null,
            sendtTilNAVDato: null,
            sendtTilArbeidsgiverDato: null,
            avbruttDato: null,
            startSykeforlop: '2019-05-07',
            sykmeldingUtskrevet: '2019-05-11',
            arbeidsgiver: {
                navn: 'ÅSEN BOFELLESSKAP',
                orgnummer: '995816598',
            },
            korrigerer: null,
            korrigertAv: null,
            arbeidssituasjon: 'ARBEIDSTAKER',
            soknadPerioder: [{
                fom: '2019-05-11',
                tom: '2019-05-19',
                grad: 40,
            }],
            sporsmal: [{
                id: '215252',
                tag: 'ANSVARSERKLARING',
                sporsmalstekst: 'Jeg vet at jeg kan miste retten til sykepenger hvis opplysningene jeg gir ikke er riktige eller fullstendige. Jeg vet også at NAV kan holde igjen eller kreve tilbake penger, og at å gi feil opplysninger kan være straffbart.',
                undertekst: null,
                svartype: 'CHECKBOX_PANEL',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: null,
                svar: [{
                    verdi: 'CHECKED',
                }],
                undersporsmal: [],
            }, {
                id: '215253',
                tag: 'EGENMELDINGER',
                sporsmalstekst: 'Vi har registrert at du ble sykmeldt tirsdag 7. mai 2019. Brukte du egenmeldinger og/eller var du sykmeldt i perioden 21. april - 6. mai 2019?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [{
                    verdi: 'NEI',
                }],
                undersporsmal: [{
                    id: '215254',
                    tag: 'EGENMELDINGER_NAR',
                    sporsmalstekst: 'Hvilke dager før 7. mai 2019 var du borte fra jobb?',
                    undertekst: null,
                    svartype: 'PERIODER',
                    min: '2018-11-07',
                    max: '2019-05-06',
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                }],
            }, {
                id: '215255',
                tag: 'TILBAKE_I_ARBEID',
                sporsmalstekst: 'Var du tilbake i fullt arbeid hos ÅSEN BOFELLESSKAP før 20. mai 2019?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: true,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [{
                    verdi: 'NEI',
                }],
                undersporsmal: [{
                    id: '215256',
                    tag: 'TILBAKE_NAR',
                    sporsmalstekst: 'Når begynte du å jobbe igjen?',
                    undertekst: null,
                    svartype: 'DATO',
                    min: '2019-05-11',
                    max: '2019-05-19',
                    pavirkerAndreSporsmal: true,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                }],
            }, {
                id: '215263',
                tag: 'JOBBET_DU_GRADERT_0',
                sporsmalstekst: 'I perioden 11. - 19. mai 2019 skulle du jobbe 60 % av ditt normale arbeid hos ÅSEN BOFELLESSKAP. Jobbet du mer enn dette?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [{
                    verdi: 'JA',
                }],
                undersporsmal: [{
                    id: '215264',
                    tag: 'HVOR_MANGE_TIMER_PER_UKE_0',
                    sporsmalstekst: 'Hvor mange timer jobbet du per uke før du ble sykmeldt?',
                    undertekst: 'timer per uke',
                    svartype: 'TALL',
                    min: '1',
                    max: '150',
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{
                        verdi: '37,5',
                    }],
                    undersporsmal: [],
                }, {
                    id: '215265',
                    tag: 'HVOR_MYE_HAR_DU_JOBBET_0',
                    sporsmalstekst: 'Hvor mye jobbet du totalt 11. - 19. mai 2019 hos ÅSEN BOFELLESSKAP?',
                    undertekst: null,
                    svartype: 'RADIO_GRUPPE_TIMER_PROSENT',
                    min: null,
                    max: null,
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [{
                        id: '215266',
                        tag: 'HVOR_MYE_PROSENT_0',
                        sporsmalstekst: 'prosent',
                        undertekst: null,
                        svartype: 'RADIO',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [],
                        undersporsmal: [{
                            id: '215267',
                            tag: 'HVOR_MYE_PROSENT_VERDI_0',
                            sporsmalstekst: null,
                            undertekst: 'prosent',
                            svartype: 'TALL',
                            min: '61',
                            max: '99',
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                        }],
                    }, {
                        id: '215268',
                        tag: 'HVOR_MYE_TIMER_0',
                        sporsmalstekst: 'timer',
                        undertekst: null,
                        svartype: 'RADIO',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [{
                            verdi: 'CHECKED',
                        }],
                        undersporsmal: [{
                            id: '215269',
                            tag: 'HVOR_MYE_TIMER_VERDI_0',
                            sporsmalstekst: null,
                            undertekst: 'timer totalt',
                            svartype: 'TALL',
                            min: '1',
                            max: '193',
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [{
                                verdi: '10',
                            }],
                            undersporsmal: [],
                        }],
                    }],
                }],
            }, {
                id: '215270',
                tag: 'ANDRE_INNTEKTSKILDER',
                sporsmalstekst: 'Har du andre inntektskilder enn ÅSEN BOFELLESSKAP?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [],
                undersporsmal: [{
                    id: '215271',
                    tag: 'HVILKE_ANDRE_INNTEKTSKILDER',
                    sporsmalstekst: 'Hvilke andre inntektskilder har du?',
                    undertekst: 'Du trenger ikke oppgi penger fra NAV',
                    svartype: 'CHECKBOX_GRUPPE',
                    min: null,
                    max: null,
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [{
                        id: '215272',
                        tag: 'INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD',
                        sporsmalstekst: 'andre arbeidsforhold',
                        undertekst: null,
                        svartype: 'CHECKBOX',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [],
                        undersporsmal: [{
                            id: '215273',
                            tag: 'INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD_ER_DU_SYKMELDT',
                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                            undertekst: null,
                            svartype: 'JA_NEI',
                            min: null,
                            max: null,
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                        }],
                    }, {
                        id: '215274',
                        tag: 'INNTEKTSKILDE_SELVSTENDIG',
                        sporsmalstekst: 'selvstendig næringsdrivende',
                        undertekst: null,
                        svartype: 'CHECKBOX',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [],
                        undersporsmal: [{
                            id: '215275',
                            tag: 'INNTEKTSKILDE_SELVSTENDIG_ER_DU_SYKMELDT',
                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                            undertekst: null,
                            svartype: 'JA_NEI',
                            min: null,
                            max: null,
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                        }],
                    }, {
                        id: '215276',
                        tag: 'INNTEKTSKILDE_SELVSTENDIG_DAGMAMMA',
                        sporsmalstekst: 'dagmamma',
                        undertekst: null,
                        svartype: 'CHECKBOX',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [],
                        undersporsmal: [{
                            id: '215277',
                            tag: 'INNTEKTSKILDE_SELVSTENDIG_DAGMAMMA_ER_DU_SYKMELDT',
                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                            undertekst: null,
                            svartype: 'JA_NEI',
                            min: null,
                            max: null,
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                        }],
                    }, {
                        id: '215278',
                        tag: 'INNTEKTSKILDE_JORDBRUKER',
                        sporsmalstekst: 'jordbruk / fiske / reindrift',
                        undertekst: null,
                        svartype: 'CHECKBOX',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [],
                        undersporsmal: [{
                            id: '215279',
                            tag: 'INNTEKTSKILDE_JORDBRUKER_ER_DU_SYKMELDT',
                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                            undertekst: null,
                            svartype: 'JA_NEI',
                            min: null,
                            max: null,
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                        }],
                    }, {
                        id: '215280',
                        tag: 'INNTEKTSKILDE_FRILANSER',
                        sporsmalstekst: 'frilanser',
                        undertekst: null,
                        svartype: 'CHECKBOX',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [],
                        undersporsmal: [{
                            id: '215281',
                            tag: 'INNTEKTSKILDE_FRILANSER_ER_DU_SYKMELDT',
                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                            undertekst: null,
                            svartype: 'JA_NEI',
                            min: null,
                            max: null,
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                        }],
                    }, {
                        id: '215282',
                        tag: 'INNTEKTSKILDE_ANNET',
                        sporsmalstekst: 'annet',
                        undertekst: null,
                        svartype: 'CHECKBOX',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: null,
                        svar: [],
                        undersporsmal: [],
                    }],
                }],
            }, {
                id: '215283',
                tag: 'UTDANNING',
                sporsmalstekst: 'Har du vært under utdanning i løpet av perioden 11. - 19. mai 2019?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [],
                undersporsmal: [{
                    id: '215284',
                    tag: 'UTDANNING_START',
                    sporsmalstekst: 'Når startet du på utdanningen?',
                    undertekst: null,
                    svartype: 'DATO',
                    min: null,
                    max: '2019-05-19',
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                }, {
                    id: '215285',
                    tag: 'FULLTIDSSTUDIUM',
                    sporsmalstekst: 'Er utdanningen et fulltidsstudium?',
                    undertekst: null,
                    svartype: 'JA_NEI',
                    min: null,
                    max: null,
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                }],
            }, {
                id: '215286',
                tag: 'VAER_KLAR_OVER_AT',
                sporsmalstekst: 'Viktig å være klar over:',
                undertekst: '<ul><li>Du kan bare få sykepenger hvis det er din egen sykdom eller skade som hindrer deg i å jobbe. Sosiale eller økonomiske problemer gir ikke rett til sykepenger.</li><li>Du kan miste retten til sykepenger hvis du nekter å opplyse om din egen arbeidsevne, eller hvis du ikke tar imot behandling eller tilrettelegging.</li><li>Retten til sykepenger gjelder bare inntekt du har mottatt som lønn og betalt skatt av på sykmeldingstidspunktet.</li><li>NAV kan innhente opplysninger som er nødvendige for å behandle søknaden.</li><li>Du må melde fra til NAV hvis du satt i varetekt, sonet straff eller var under forvaring i sykmeldingsperioden.</li><li>Fristen for å søke sykepenger er som hovedregel 3 måneder</li></ul><p>Du kan lese mer om rettigheter og plikter på <a href="https://www.nav.no/sykepenger" target="_blank">nav.no/sykepenger</a>.</p>',
                svartype: 'IKKE_RELEVANT',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: null,
                svar: [],
                undersporsmal: [],
            }, {
                id: '215287',
                tag: 'BEKREFT_OPPLYSNINGER',
                sporsmalstekst: 'Jeg har lest all informasjonen jeg har fått i søknaden og bekrefter at opplysningene jeg har gitt er korrekte.',
                undertekst: null,
                svartype: 'CHECKBOX_PANEL',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: null,
                svar: [],
                undersporsmal: [],
            }],
        };
        const values = fraBackendsoknadTilInitiellSoknad(soknad);
        const feilmeldinger = validerGraderteArbeidssporsmal(soknad.sporsmal, values, parseSoknad(soknad));
        expect(feilmeldinger.HVOR_MYE_TIMER_VERDI_0).not.to.equal(undefined);
    });

    it('Skal ikke med ferie- og permisjonsperioder i beregning av arbeidsgrad dersom søknad inneholder FERIE_PERM_UTLAND-spørsmålet', () => {
        const soknad = {
            id: 'a4f27ba1-f850-49f0-b314-20b1564b2ef8',
            aktorId: '1924473393808',
            sykmeldingId: '2f3582db-5713-48d4-9de7-286b45886215',
            soknadstype: 'ARBEIDSTAKERE',
            status: 'NY',
            fom: '2019-05-11',
            tom: '2019-05-19',
            opprettetDato: '2019-05-20',
            innsendtDato: null,
            sendtTilNAVDato: null,
            sendtTilArbeidsgiverDato: null,
            avbruttDato: null,
            startSykeforlop: '2019-05-07',
            sykmeldingUtskrevet: '2019-05-11',
            arbeidsgiver: {
                navn: 'ÅSEN BOFELLESSKAP',
                orgnummer: '995816598',
            },
            korrigerer: null,
            korrigertAv: null,
            arbeidssituasjon: 'ARBEIDSTAKER',
            soknadPerioder: [{
                fom: '2019-05-11',
                tom: '2019-05-19',
                grad: 40,
            }],
            sporsmal: [{
                id: '215252',
                tag: 'ANSVARSERKLARING',
                sporsmalstekst: 'Jeg vet at jeg kan miste retten til sykepenger hvis opplysningene jeg gir ikke er riktige eller fullstendige. Jeg vet også at NAV kan holde igjen eller kreve tilbake penger, og at å gi feil opplysninger kan være straffbart.',
                undertekst: null,
                svartype: 'CHECKBOX_PANEL',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: null,
                svar: [{
                    verdi: 'CHECKED',
                }],
                undersporsmal: [],
            }, {
                id: '215253',
                tag: 'EGENMELDINGER',
                sporsmalstekst: 'Vi har registrert at du ble sykmeldt tirsdag 7. mai 2019. Brukte du egenmeldinger og/eller var du sykmeldt i perioden 21. april - 6. mai 2019?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [{
                    verdi: 'NEI',
                }],
                undersporsmal: [{
                    id: '215254',
                    tag: 'EGENMELDINGER_NAR',
                    sporsmalstekst: 'Hvilke dager før 7. mai 2019 var du borte fra jobb?',
                    undertekst: null,
                    svartype: 'PERIODER',
                    min: '2018-11-07',
                    max: '2019-05-06',
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                }],
            }, {
                id: '215255',
                tag: 'TILBAKE_I_ARBEID',
                sporsmalstekst: 'Var du tilbake i fullt arbeid hos ÅSEN BOFELLESSKAP før 20. mai 2019?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: true,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [{
                    verdi: 'NEI',
                }],
                undersporsmal: [{
                    id: '215256',
                    tag: 'TILBAKE_NAR',
                    sporsmalstekst: 'Når begynte du å jobbe igjen?',
                    undertekst: null,
                    svartype: 'DATO',
                    min: '2019-05-11',
                    max: '2019-05-19',
                    pavirkerAndreSporsmal: true,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [],
                }],
            }, {
                id: '215263',
                tag: 'JOBBET_DU_GRADERT_0',
                sporsmalstekst: 'I perioden 11. - 19. mai 2019 skulle du jobbe 60 % av ditt normale arbeid hos ÅSEN BOFELLESSKAP. Jobbet du mer enn dette?',
                undertekst: null,
                svartype: 'JA_NEI',
                min: null,
                max: null,
                pavirkerAndreSporsmal: false,
                kriterieForVisningAvUndersporsmal: 'JA',
                svar: [{
                    verdi: 'JA',
                }],
                undersporsmal: [{
                    id: '215264',
                    tag: 'HVOR_MANGE_TIMER_PER_UKE_0',
                    sporsmalstekst: 'Hvor mange timer jobbet du per uke før du ble sykmeldt?',
                    undertekst: 'timer per uke',
                    svartype: 'TALL',
                    min: '1',
                    max: '150',
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{
                        verdi: '37,5',
                    }],
                    undersporsmal: [],
                }, {
                    id: '215265',
                    tag: 'HVOR_MYE_HAR_DU_JOBBET_0',
                    sporsmalstekst: 'Hvor mye jobbet du totalt 11. - 19. mai 2019 hos ÅSEN BOFELLESSKAP?',
                    undertekst: null,
                    svartype: 'RADIO_GRUPPE_TIMER_PROSENT',
                    min: null,
                    max: null,
                    pavirkerAndreSporsmal: false,
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [{
                        id: '215266',
                        tag: 'HVOR_MYE_PROSENT_0',
                        sporsmalstekst: 'prosent',
                        undertekst: null,
                        svartype: 'RADIO',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [],
                        undersporsmal: [{
                            id: '215267',
                            tag: 'HVOR_MYE_PROSENT_VERDI_0',
                            sporsmalstekst: null,
                            undertekst: 'prosent',
                            svartype: 'TALL',
                            min: '61',
                            max: '99',
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                        }],
                    }, {
                        id: '215268',
                        tag: 'HVOR_MYE_TIMER_0',
                        sporsmalstekst: 'timer',
                        undertekst: null,
                        svartype: 'RADIO',
                        min: null,
                        max: null,
                        pavirkerAndreSporsmal: false,
                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                        svar: [{
                            verdi: 'CHECKED',
                        }],
                        undersporsmal: [{
                            id: '215269',
                            tag: 'HVOR_MYE_TIMER_VERDI_0',
                            sporsmalstekst: null,
                            undertekst: 'timer totalt',
                            svartype: 'TALL',
                            min: '1',
                            max: '193',
                            pavirkerAndreSporsmal: false,
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [{
                                verdi: '10',
                            }],
                            undersporsmal: [],
                        }],
                    }],
                }],
            }, {
                tag: 'FERIE_PERMISJON_UTLAND',
                undersporsmal: [],
                svar: [],
            }],
        };
        const values = fraBackendsoknadTilInitiellSoknad(soknad);
        const feilmeldinger = validerGraderteArbeidssporsmal(soknad.sporsmal, values, parseSoknad(soknad));
        expect(feilmeldinger.HVOR_MYE_TIMER_VERDI_0).to.equal(undefined);
    });

    /* eslint-enable max-len */
});
