export const ARBEIDSSITUASJON_SELVSTENDIG = 'NAERINGSDRIVENDE';
export const ARBEIDSSITUASJON_FRILANSER = 'FRILANSER';
export const ARBEIDSSITUASJON_ARBEIDSTAKER = 'ARBEIDSTAKER';
export const ARBEIDSSITUASJON_ARBEIDSLEDIG = 'ARBEIDSLEDIG';
export const ARBEIDSSITUASJON_ANNET = 'ANNET';
