export const SELVSTENDIGE_OG_FRILANSERE = 'SELVSTENDIGE_OG_FRILANSERE';
export const OPPHOLD_UTLAND = 'OPPHOLD_UTLAND';
export const ARBEIDSTAKERE = 'ARBEIDSTAKERE';
export const ARBEIDSLEDIG = 'ARBEIDSLEDIG';
export const BEHANDLINGSDAGER = 'BEHANDLINGSDAGER';
export const ANNET_ARBEIDSFORHOLD = 'ANNET_ARBEIDSFORHOLD';
