name: Deploy til heroku
on:
  push:
    branches:
      - 'master'
env:
  HEROKU_APP: sykepengesoknad
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
jobs:
  build-and-publish:
    name: Bygg, test og push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install npm dependencies
        run: npm i
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build application
        run: npm run nais-build
      - name: Build Docker image
        run: docker build -t sykepengesoknad -f Dockerfile.web --build-arg BASE_IMAGE_PREFIX=node .
      - name: Login into Heroku
        uses: actions/heroku@master
        with:
          args: container:login
      - name: Push to Heroku
        uses: actions/heroku@master
        with:
          args: container:push web  --recursive
      - name: Trigger release in Heroku
        uses: actions/heroku@master
        with:
          args: container:release web
