name: Bygg, publish og deploy
on: push
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/sykepengesoknad:${{ github.sha }}
jobs:
  build-and-publish:
    name: Bygg, test og push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install npm dependencies
        run: npm i
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build application
        run: npm run nais-build
      - name: Build and publish Docker image
        env:
          NAME: sykepengesoknad
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        run: |
          docker build -t ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}

  deploy-to-dev-sbs:
    name: Deploy til dev-sbs (Q1)
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        name: Deploy to dev-sbs
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: nais-dev.yaml

  deploy-to-prod-sbs:
    if: github.ref == 'refs/heads/master'
    name: Deploy til prod-sbs (Produksjon)
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        name: Deploy to prod-sbs
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-sbs
          RESOURCE: nais-prod.yaml
